# Generated by Django 2.2.5 on 2019-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('review', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.ManyToManyField(to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.ManyToManyField(to='review.Review'),
        ),
    ]
