# Generated by Django 2.2.5 on 2019-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('author', '0001_initial'),
        ('core', '0002_auto_20190911_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='author.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
